### PR TITLE
Added pyml2ds module

### PR DESCRIPTION
**Pull request by InvalidPointer**
First draft. Please review and give some comments to help to improve my module.

### CODE REVIEW

**Comment by jlwalke2** [comment]
Looking good so far.  Here are a few suggestions to think about:

1.  Don't assume 3rd party packages are installed (unless listed in setup.py).  If an external package like xgboost is required for specific functionality, it's fine to check for it and raise an error if not present, but this should happen when _used_ not when imported.  See [core.py](https://github.com/sassoftware/python-sasctl/blob/master/src/sasctl/core.py) for an example of how `Session` does this with the `swat` and `kerberos` modules.

2. It looks like `TreeParser` is intended to be an abstract base class.  If so, it should be a little more obvious that this class can't be instantiated and used on it's own.  The official way is to [decorate the class](https://stackoverflow.com/questions/13646245/is-it-possible-to-make-abstract-classes-in-python), although to support Python 2.7 you'd [need to use six](https://stackoverflow.com/questions/35673474/using-abc-abcmeta-in-a-way-it-is-compatible-both-with-python-2-7-and-python-3-5).  At minimum though, I'd at least recommend raising `NotImplementedError` instead of `pass`ing.

3.  Since the `py2sas` functionality is being merged with a larger module, I'd recommend changing the naming to something that more clearly indicates that the functionality is for converting Python models to equivalent SAS code (currently supported for xgboost and lightgbm).


There are also a few requirements that will have to be met when you're ready for the code to be merged.  These are hopefully all documented in the [Contributor Guide](https://sassoftware.github.io/python-sasctl/#contributor-guide), but basically the code will need to include:

- docstrings on public classes and methods
- unit tests

**Comment by InvalidPointer** [comment]
Improved things that you've mentioned. Please, take a look. Thanks!

Also, do you have any ideas how tests for this module should look like? I would be really glad for your help.

**Comment by jlwalke2** [comment]
Since all of the new functionality is going into `.utils`, you can probably test most of the functionality with simple unit tests, instead of having to worry about integration tests, session management, etc.

The PyMAS functionality in `.utils` is similar in that regard, so you can look at those [unit tests](https://github.com/sassoftware/python-sasctl/blob/master/tests/unit/test_pymas.py) for some examples

**Comment by InvalidPointer** [comment]
@jlwalke2 Is there possibility to switch Travis to Ubuntu 16? I suppose it should help.

https://github.com/dmlc/xgboost/issues/4489

**Comment by InvalidPointer** [comment]
Or I can switch xgboost to older version for tests..

**Comment by InvalidPointer** [comment]
Something strange.. it fails where it didn’t fail last time.

**Comment by jlwalke2** [comment]
Don't worry about it - it's not an issue with your code.

The build is "failing" because the execution of the tests against Python 3.4 timed out.  Unfortunately, this seems to happen fairly often; for some reason setting up the 3.4 environment in Travis is extremely slow, and Travis terminates a build job if it doesn't make any progress in 10 minutes.

If you look [here](https://travis-ci.com/sassoftware/python-sasctl/jobs/241176326) you can see that the job was terminated early.

It might make sense to only run checks against Py 3.4 for tagged releases instead of all commits, but I haven't had a chance to monkey with the configuration yet.

**Comment by InvalidPointer** [comment]
@jlwalke2 Is there anything else should be done before merging?

**Pull request merged**
